nx_file=/data/visitor/ihmi1611/id16a/20260428//PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001/projections/SiemensStar_pseudorandom_010nm_0001_scan0001.nx

h5_out=/data/visitor/ihmi1611/id16a/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001/phasing/nfp_results.h5
path_out=/data/visitor/ihmi1611/id16a/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001/phasing/

n=4096
niter=513
nchunk=4
vis_step=-1
err_step=16
rho=1,2,0.1
log_level=INFO
