nx_file=/data3/vnikitin/ESRF_Apr2026/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001/projections/SiemensStar_pseudorandom_010nm_0001_scan0001.nx
h5_out=/data3/vnikitin/ESRF_Apr2026/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001_rec/nfp_results.h5
path_out=/data3/vnikitin/ESRF_Apr2026_rec/20260428/SiemensStar/SiemensStar_pseudorandom_010nm_0001_rec/

n=4096
niter=513
nchunk=4
vis_step=16
err_step=16
rho=1,2,0.1
log_level=INFO
