in_file=/eagle/APS_IRI/vnikitin/20231007/y350a_80um_rec/y350a_80um_4k_08nm.h5 # input h5 dataset
path_out=/eagle/APS_IRI/vnikitin/20231007/y350a_80um_rec/ # path to save results
prb_file=/eagle/APS_IRI/vnikitin/20231007/y350a_80um_rec/nfp_results.h5 # NFP probe initial guess
#init_vol= # initial object guess from external reconstruction (.vol binary file)

nchunk=4              # chunk size to fit to GPU
ntheta=4000           # number of projection angles
niter=513               # number of iterations
vis_step=32           # save results every N iters (-1 = disabled)
err_step=32            # show error every N iters
nz=1536               # vertical detector size
n=1536                # horizontal detector size
nzobj=2500           # vertical object size
nobj=2500            # horizontal object size (in x and y)
bin=2
start_theta=0
ndist=4               # number of distances
rotation_center_shift=35.66
obj_dtype=complex64
paganin=27            # Paganin constant to read initial guess from file
mask=-1               # mask radius for tomography (-1 = no mask)
lam_prbfit=3.1e-3     # probe fit term weight
lam_laplacian=0       # 3-D Laplacian regularization weight
rho=1,0.05,0.02       # gradient step scaling: object, probe, positions
start_iter=0
log_level=INFO
energy=33.35
