in_file=/data3/vnikitin/atomium/20240924/AtomiumS2_new_rec/AtomiumS2_HT_007nm.h5 # input h5 dataset
path_out=/data3/vnikitin/atomium/20240924/AtomiumS2_new_rec/ # path to save results

nchunk=2              # chunk size to fit to GPU
ntheta=1800           # number of projection angles
niter=2048            # number of iterations
vis_step=32           # save results every N iters (-1 = disabled)
err_step=32           # show error every N iters (-1 = disabled)
nz=2048               # vertical detector size
n=2048                # horizontal detector size
nzobj=3264            # vertical object size
nobj=3264             # horizontal object size (in x and y)
bin=0
start_theta=0
ndist=4               # number of distances
rotation_center_shift=-27.00227
obj_dtype=complex64
paganin=120           # Paganin constant to read initial guess from file
mask=1.1              # mask radius for tomography
lam_prbfit=3.1e-3     # probe fit term weight
lam_laplacian=0       # 3-D Laplacian regularization weight
rho=1,0.05,0.02       # gradient step scaling: object, probe, positions
start_iter=0
log_level=WARNING
energy=33.6
