# For performance tests modify this
in_file=/data2/vnikitin/brain_rec/20251115/Y350a/data_brainY350a_dist1234.h5 # input h5 dataset
path_out=/data2/vnikitin/test1 # path to save results
nchunk=8 # chunk size to fit to GPU
ntheta=900 # number of projection angles (max 4500)
niter=10 # Number of iterations
vis_step=4 # save results step (-1 - no save)
err_step=1 # show error step (-1 - no error computation, we typically set 32)
nz=1024 # vertical detector size
n=1024 # horionztal detector size
nzobj=1632 # vertical object size
nobj=1632 # horizontal object size (in x and y)
bin=1
# For performance tests the followiung should be fixed
start_theta=0 # angle to start
ndist=4 # number of distances
rotation_center_shift=-8.780113 # shift of the rotation center with respect to the detector center
obj_dtype=complex64 # object type, either complex64 or float32 (to save memory)
paganin=20 # Paganin constant to read the initial guess from file
mask=1.1 # Mask radius for tomography
lam_prbfit=3.1e-3 # Probe fit term weight
rho=1,0.05,0.02 # Scaling for variables for object, probe, and positions
start_iter=8
log_level=INFO # logging level: DEBUG, INFO, WARNING, ERROR
energy=17.23

## 0 - BH
## 1 - PR, BH step length
## 2 - PR, Wolfe step length
## 3 - LBFGS, Wolfe step length
## 4 - BH, exact line search 40 values around 0.9alpha.. 1.1alpha
## 5 - BH, Wolfe line search
## 6 - LBFGS, BH step length



