in_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a_FT_large_rand_disp_rec/Y350a_FT_large_rand_disp_nobin_020nm.h5      # raw data root
path_out=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a_FT_large_rand_disp_rec/ # path to save results
# prb_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20240515/Y350c_rec/nfp_results.h5 # NFP probe initial guess
#init_vol= # initial object guess from external reconstruction (.vol binary file)

nchunk=16              # chunk size to fit to GPU
ntheta=4000           # number of projection angles
niter=513               # number of iterations
vis_step=64           # save results every N iters (-1 = disabled)
err_step=64            # show error every N iters
nz=1024               # vertical detector size
n=1024                # horizontal detector size
nzobj=1024           # vertical object size
nobj=1024            # horizontal object size (in x and y)
bin=2
start_theta=0
ndist=1               # number of distances
rotation_center_shift=-11.79
obj_dtype=complex64
paganin=100            # Paganin constant to read initial guess from file
mask=-1               # mask radius for tomography (-1 = no mask)
lam_prbfit=3.1e-3     # probe fit term weight
lam_laplacian=0       # 3-D Laplacian regularization weight
rho=1,0.05,0.02       # gradient step scaling: object, probe, positions
start_iter=0
log_level=INFO
energy=33.35
