scan_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a/Y350a_FT_large_rand_disp_nobin_020nm_NFPwS_1_/Y350a_FT_large_rand_disp_nobin_020nm_NFPwS_1_0000.h5 # raw scan HDF5 (dataset index replaced by dataset_ids)
meta_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a/Y350a_FT_large_rand_disp_nobin_020nm_NFPwS_1_/ls3231-Y350a-Y350a_FT_large_rand_disp_nobin_020nm_NFPwS_1_.h5 #a (energy, distances, pixelsize)
h5_out=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a_FT_large_rand_disp_rec/nfp_results.h5 # output file for NFP probe and positions
path_out=/gpfs/jazzy/data/visitor/ls3231/id16a/20250604/Y350a_FT_large_rand_disp_rec/ # directory for per-iter tiff/npy/csv saves (omit or leave blank to disable)

dataset_ids=1 # distance indices: replaces _1_ in scan_file name for each distance

n=4096       # detector size (pixels)
niter=513    # number of NFP iterations
nchunk=2     # projections processed per GPU batch
vis_step=32  # save visualisation every N iters (-1 = disabled)
err_step=32  # print error every N iterations
rho=1,2,0.1  # gradient step scaling: object, probe, positions
log_level=INFO
