in_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20240515/Y350c_rec/Y350c_HT_015nm.h5     # raw data root/y350a_80um_4k_08nm.h5 # input h5 dataset
path_out=/gpfs/jazzy/data/visitor/ls3231/id16a/20240515/Y350c_rec_p0 # path to save results
# prb_file=/gpfs/jazzy/data/visitor/ls3231/id16a/20240515/Y350c_rec/nfp_results.h5 # NFP probe initial guess
#init_vol= # initial object guess from external reconstruction (.vol binary file)

nchunk=4              # chunk size to fit to GPU
ntheta=1500           # number of projection angles
niter=1000               # number of iterations
vis_step=16           # save results every N iters (-1 = disabled)
err_step=16            # show error every N iters
nz=2048               # vertical detector size
n=2048                # horizontal detector size
nzobj=2500           # vertical object size
nobj=2500            # horizontal object size (in x and y)
bin=0
start_theta=0
ndist=4               # number of distances
rotation_center_shift=145.07
obj_dtype=complex64
paganin=120            # Paganin constant to read initial guess from file
mask=1               # mask radius for tomography (-1 = no mask)
lam_prbfit=3.1e-3     # probe fit term weight
lam_laplacian=0       # 3-D Laplacian regularization weight
rho=1,0.05,0.000001       # gradient step scaling: object, probe, positions
start_iter=256
pos_checkpoint=/gpfs/jazzy/data/visitor/ls3231/id16a/20240515/Y350c_rec/checkpoint_0464.h5
log_level=INFO
energy=33.35
