# For performance tests modify this
in_file=/data2/vnikitin/syn_sample.h5 # input h5 dataset
path_out=/data2/vnikitin/syn_sample_rec2 # path to save results
nchunk=8 # chunk size to fit to GPU

ntheta=900 # number of projection angles (max 18000)
niter=257 # Number of iterations
vis_step=-1 # save results step (-1 - no save)
err_step=1 # show error step (-1 - no error computation, we typically set 32)

nz=512 # vertical detector size
n=512 # horionztal detector size
nzobj=816 # vertical object size
nobj=816 # horizontal object size (in x and y)
bin=0 # increasing data sizes n -> n*2^(unbin), initial n is 512 (unbin=0)

# For performance tests the followiung should be fixed

start_theta=0 # angle to start
ndist=4 # number of distances
rotation_center_shift=-2.170113 # shift of the rotation center with respect to the detector center
obj_dtype=complex64 # object type, either complex64 or float32 (to save memory)
paganin=20 # Paganin constant to read the initial guess from file
mask=1.1 # Mask radius for tomography
lam_reg=0 # Regularization term weight
lam_prbfit=3.1e-3 # Probe fit term weight
rho=1,0.05,0.02 # Scaling for variables for object, probe, and positions
start_iter = 0
log_level=WARNING # logging level: DEBUG, INFO, WARNING, ERROR





