
in_file=/data2/vnikitin/atomium_rec/20250607/AtomiumL1/data.h5
path_out=/data2/vnikitin/atomium_rec/20250607/AtomiumL1/run1
ntheta=360
nz=2048
n=2048
nzobj=2048
nobj=2048
start_theta=0
ndist=4
obj_dtype=complex64
paganin=80
mask=0.9
lam_reg=0
lam_prbfit=1e-3
rho=1,0.1,0.1
nbins=1
niter=257,193,513
nchunk=2,8,32
vis_step=-1,-1,-1
err_step=32,32,4
clean_cache_step=16,-1,-1
start_bin=2
start_iter=-1
rotation_center_shift = -14.621



